name: CMake
on:
  push:
    branches: cmake_dev
jobs:
  build-project:
    name: Build Project
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: "Install doxygen"
        uses:  ssciwr/doxygen-install@v1.5

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
        with:
            build-dir: build
            generator: "Visual Studio 17 2022"
